In [1]:
import tensorflow as tf
import numpy as np

# Operation range, Broadcasting

In [2]:
t1 = tf.constant([1, 2, 3])
t2 = tf.constant([10, 20, 30])
print(t1 + t2)

l1 = [1, 2, 3]
l2 = [10, 20, 30]
print(l1 + l2)
# python list sum -> concatenation
# tf constant sum -> element-wise sum
# tf operations do in level of element-wise basically except for matrix operation(E.g. +, -, *, /, %, // etc.)

tf.Tensor([11 22 33], shape=(3,), dtype=int32)
[1, 2, 3, 10, 20, 30]


2022-01-10 16:51:33.351058: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [3]:
t3 = tf.random.normal(shape=(3, 4), mean=0, stddev=5)
t4 = tf.random.normal(shape=(1, 4), mean=0, stddev=5)

t3 = tf.cast(t3, dtype=tf.int16)
t4 = tf.cast(t4, dtype=tf.int16)

t5 = t3 + t4

print(t3.numpy(), '\n')
print(t4.numpy(), '\n')
print(t5.numpy(), '\n') # Broadcasting

[[ 1  0  0  4]
 [ 0  1  9 -2]
 [-4  0  0 -4]] 

[[-4  1  2  2]] 

[[-3  1  2  6]
 [-4  2 11  0]
 [-8  1  2 -2]] 



# Reduce function

Reduce function operates while corporating dimensions

- tf.reduce_sum
- tf.reduce_prod

- tf.reduce_max
- tf.reduce_min

- tf.reduce_mean
- tf.reduce_std
- tf.reduce_variance

- tf.reduce_all
- tf.reduce_any

In [4]:
t6 = tf.reduce_sum(t3) # sum all elements
print(t3)
print(t6)

tf.Tensor(
[[ 1  0  0  4]
 [ 0  1  9 -2]
 [-4  0  0 -4]], shape=(3, 4), dtype=int16)
tf.Tensor(5, shape=(), dtype=int16)


In [5]:
t7 = tf.reduce_sum(t3, axis = 0) # Do summation by removing axis 0. {shape = (3, 4)}
print(t3)
print(t7)

tf.Tensor(
[[ 1  0  0  4]
 [ 0  1  9 -2]
 [-4  0  0 -4]], shape=(3, 4), dtype=int16)
tf.Tensor([-3  1  9 -2], shape=(4,), dtype=int16)
