In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from tensorflow.keras.losses import BinaryCrossentropy
from tensorflow.keras.losses import CategoricalCrossentropy
from tensorflow.keras.losses import SparseCategoricalCrossentropy

In [3]:
from tensorflow.keras.metrics import CategoricalAccuracy
from tensorflow.keras.metrics import SparseCategoricalAccuracy

In [4]:
loss_object = BinaryCrossentropy()

In [5]:
predictions = np.array([0.3, 0.6]).reshape(-1, 1)
labels = np.array([1, 0]).reshape(-1, 1)

loss = loss_object(labels, predictions)
loss

<tf.Tensor: shape=(), dtype=float64, numpy=1.0601314306259155>

In [6]:
predictions = tf.constant([[0.3, 0.7], [0.6, 0.4]])
labels = tf.constant([[0, 1], [1, 0]])

loss = loss_object(labels, predictions)
loss

<tf.Tensor: shape=(), dtype=float32, numpy=0.4337501>

In [7]:
loss_obejct = CategoricalCrossentropy()
metric = CategoricalAccuracy()

In [8]:
predictions = tf.constant([[0.1, 0.2, 0.7], [0.6, 0.3, 0.1], [0.1, 0.8, 0.1]])
labels = tf.constant([[0, 0, 1], [0, 1, 0], [1, 0, 0]])

loss = loss_object(labels, predictions)
acc = metric(labels, predictions)
loss

<tf.Tensor: shape=(), dtype=float32, numpy=0.7697983>

In [9]:
acc

<tf.Tensor: shape=(), dtype=float32, numpy=0.33333334>

In [10]:
loss_object = SparseCategoricalCrossentropy()
metric = SparseCategoricalAccuracy()

In [11]:
predictions = tf.constant([[0.1, 0.2, 0.7], [0.6, 0.3, 0.1], [0.1, 0.8, 0.1]])
labels = tf.constant([2, 1, 0])

loss = loss_object(labels, predictions)
acc = metric(labels, predictions)
loss

<tf.Tensor: shape=(), dtype=float32, numpy=1.2877443>

In [12]:
acc

<tf.Tensor: shape=(), dtype=float32, numpy=0.33333334>